### ISSUE TITLE
Is that possible to get digital ECG data from this website?

### ISSUE THREAD

**Issue by sandhyasurendararaj** [MIT-LCP/physionet#103]

**Comment by alistairewj** [comment]
Yes. https://physionet.org/

**Comment by sandhyasurendararaj** [comment]
Hi,

Thank you for your response. I think you are telling about "raw ADC data"
option for my question. But, from that option, I am getting an analog
output. What I need is the binary output of an ECG signal to store directly
into the memory?




Kind Regards,
Sandhya S
