### ISSUE TITLE
error downloading mimic3 file, files misnamed

### ISSUE THREAD

**Issue by deyehaus** [MIT-LCP/physionet#114]
Upon using wfdb.io.dl_database() attempting to download mimic3wdb/30/ it returns the following error "404 Client Error: Not Found for url: http://physionet.org/physiobank/database/mimic3wdb/30/3000031/3000031.hea", when I manually accessed the file using your web based file browser I saw that the file was actually named 3000031n.hea

**Comment by tompollard** [comment]
@deyehaus these seems to be an issue with the WFDB package rather than the data itself. I've moved the issue to: https://github.com/MIT-LCP/wfdb-python/issues/175
