### ISSUE TITLE
Data Privacy

### ISSUE THREAD

**Issue by xinsu626** [MIT-LCP/physionet#118]
Can you please let me know if I am allowed to put the data on the cloud for training models(like google cloud)?

**Comment by alistairewj** [comment]
Which dataset are you working with? It depends on the license associated with the data.

**Comment by xinsu626** [comment]
@alistairewj I am using Mimic-iii. Thank you.

**Comment by alistairewj** [comment]
For MIMIC-III, you should use our instances. Please contact mimic-support@physionet.org to receive access to the BigQuery instance - copy in your Google account e-mail and your PhysioNet credentialed e-mail.

**Comment by xinsu626** [comment]
Please correct me if I am wrong. My understanding of using your Bigquery instance is that I can only do analysis there and I am not allowed to put the data on my google cloud instance. 

Since I am planning to upload the processed mimic-iii data to my google cloud Compute Engine instance and use several google TPUs there to train a fairly large machine learning model. Can you please let me know if this plan is doable based on your data privacy policy? Thank you.

**Comment by tompollard** [comment]
@xinsu626 your suggested work plan should be doable. the data is hosted on our bigquery project, but you can save derived tables and manage additional resources via your own project.
