### ISSUE TITLE
Unable to view DB tables and Views after login to Query Builder

### ISSUE THREAD

**Issue by sonal051** [MIT-LCP/physionet#12]
![error](https://cloud.githubusercontent.com/assets/18608197/18526110/470be758-7a8d-11e6-9de4-a5d860a928ba.png)

Iam getting above error after login to query Builder.
Could you please help me with this.

**Comment by tompollard** [comment]
This version of the querybuilder has been replaced with the version linked from: http://mimic.physionet.org/gettingstarted/querybuilder/
