### ISSUE TITLE
As an independent learner, can I register for CITI training as an MIT Affiliate?

### ISSUE THREAD

**Issue by kirtisinghnitj15** [MIT-LCP/physionet#133]
Hi,
I want to access one of the restricted dataset provided by physionet which is required my account to be credentialed and regarding that physionet mentioned to do a course from CITI program but in the instructions it is given to choose MIT as an affiliation but my college is not affiliated with MIT or the CITI program. So i logged in CITI program as an independent learner but in that section same course is not provided. So i want to ask which course can i complete to access the restricted dataset. 
The attached file shows the available program for an independent learner.
Please do reply. Thank you
![hsr_IL](https://user-images.githubusercontent.com/54430158/122927935-fc7c1200-d386-11eb-9441-47d0aecde5e5.png)

**Comment by tompollard** [comment]
Please follow the instructions at https://physionet.org/about/citi-course/ to register as an MIT Affiliate. You are affiliating with MIT for the purpose of accessing data on our servers.

**Comment by kirtisinghnitj15** [comment]
ok sir, so there will be no issue in accessing restricted data from physionet even if I am not a student of MIT or any other organization that is affiliated with the CITI program.

**Comment by briangow** [comment]
Correct, you do not need to be a student or employee at MIT to register as an affiliate.

**Comment by kirtisinghnitj15** [comment]
Thank you so much for the clarification @briangow
