### ISSUE TITLE
MIMIC III Waveform Database Matched Subset

### ISSUE THREAD

**Issue by swesh77** [MIT-LCP/physionet#137]

**Comment by tompollard** [comment]
The dataset is available on PhysioNet: https://physionet.org/content/mimic3wdb-matched/1.0/

**Comment by swesh77** [comment]
Is there an easier way to download it? I keep getting an error when I download it on rsync I also don’t have Physionet credentials so I cant link it to cloud or AWS S3

**Comment by tompollard** [comment]
Downloading from Google Cloud with gsutil is probably the quickest way (commands are shown in the Files section). You could also try wget, which is slower but doesn't require you to have a Google Cloud account.

**Comment by swesh77** [comment]
What are the commands to retrieve it from wget?

**Comment by tompollard** [comment]
Scroll to the "Files" section for the project and you'll see the different options.

![Screen Shot 2022-02-12 at 23 10 20](https://user-images.githubusercontent.com/822601/153738236-2d5997dc-ae81-4897-b12d-85f2fad83ae5.png)

**Comment by swesh77** [comment]
Ok thanks I'll try this.
