### ISSUE TITLE
Report status of data use applications to applicants

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet#14]
We receive emails from people who have applied for access to MIMIC and who are asking for updates on the status of their application. Often our response is that we awaiting approval from their supervisor. It would be good if we could provide a detailed status indicator via the website.

**Comment by kpierceHST** [comment]
No, because we don't want people to try to game the system.  Only in some cases do I contact their supervisors, and I don't necessarily want to let them know that I'm doing so.

Ken

**Comment by tompollard** [comment]
Okay Ken, closing issue.
