### ISSUE TITLE
wget timeout

### ISSUE THREAD

**Issue by mahela97** [MIT-LCP/physionet#146]
Hi,

I am trying to download mimic cxr dataset using wget using a remote server. But it gets timeout. I can visit the physionet website but wget get timeout. Is there any solution for that? thanks

**Comment by bemoody** [comment]
Please be more specific.  What happens when you run a command like this?

wget https://physionet.org/files/mitdb/1.0.0/100.hea

Copy and paste the exact error message you see.  Otherwise, we have no
way to tell what is wrong.

**Comment by mahela97** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/61684744/192603889-f57356eb-6b92-42d9-92d1-2f4e13dd54ad.png">


Thanks for the reply. I have attached a photo. This gets timeout after few time. There is no error message . Please check the below attatchment 

<img width="388" alt="image" src="https://user-images.githubusercontent.com/61684744/192604165-f2af6205-6779-4c89-8826-597256ad3db4.png">
