### ISSUE TITLE
Main Page 404

### ISSUE THREAD

**Issue by lidl2019** [MIT-LCP/physionet#155]
Hi there, I am trying to download the EEG dataset from physionet. It seems that currently the service is unavailable as I am receiving timeout error codes. Is there any alternative ways of downloading or when can I expect the service to be on?

Thanks

**Comment by tompollard** [comment]
Yesterday we experienced a power outage that impacted our network operations, apologies. The server has now been restored. For faster downloads, we recommend the cloud option, where available (located in the "Files" section).

Note that not every dataset is currently synchronized with our cloud storage. If you are unable to find a cloud access option for a specific dataset, please let us us so we can provide you with this capability.
