### ISSUE TITLE
Corrupt data files in Physionet MIT BIH Polysomnographic Database (slpdb)

### ISSUE THREAD

**Issue by mansirankawat** [MIT-LCP/physionet#17]
It seems that the MIT BIH Polysomnographic dataset here (https://www.physionet.org/physiobank/database/slpdb/) has corrupted datafiles. We downloaded the dataset using the recommended methods and on loading the annotations via rdann just gives constant values like 50 etc. The signal itself is just a straight line inclined at 45 degree.

**Comment by alistairewj** [comment]
Could you post code and small examples of the data that you try to load? A
straight line at 45 degrees sounds like the time column plotted against the
index, which may happen as it's the first column output.

**Comment by mansirankawat** [comment]
Yes in case of loading signal you are right. I was plotting the first output which is time. I corrected that and can see the signal now. But the problem with reading annotations via rdann still remains.
[a1]=rdann('slp01a', 'ecg')

returns
a1 =

   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50
   50

**Comment by alistairewj** [comment]
Looks like you've found a bug in the MATLAB toolbox. I checked and with the linux tool `rdann` everything is fine:

```
rdann -r slp01a -a ecg | head
[23:07:00.076 19/01/1989]       19     N    0    0    0
[23:07:00.936 19/01/1989]      234     N    0    0    0
[23:07:01.828 19/01/1989]      457     N    0    0    0
```

But with the MATLAB toolbox:

```matlab
ann=rdann('slp01a', 'ecg');
ann(1:5)
```
```
ans =

    50
    50
    50
    50
    50
```

Interestingly, the MATLAB toolbox works fine if you include all the output arguments:

```matlab
[ann,type,subtype,chan,num,comments]=rdann('slp01a', 'ecg');
ann(1:5)
```
```
ans =

    20
   235
   458
   688
   912
```

I'll raise this over at the WFDB for MATLAB page (https://github.com/ikarosilva/wfdb-app-toolbox/) and close it here (since the data on PhysioNet seems OK).

**Comment by mansirankawat** [comment]
Thanks a lot
