### ISSUE TITLE
Include details for new querybuilder in PhysioNet emails

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/physionet#19]
Possibly already done, but just a reminder to check that the MIMIC emails include a link to the new querybuilder tool: http://mimic.physionet.org/gettingstarted/querybuilder/

Linking with the URL above is preferable to linking to the tool directly because the webpage includes user guidelines and the location of the tool may change.

The old certificate (http://mimic.physionet.org/certs/lcpca.crt) and querybuilder tool (https://mimic2app.csail.mit.edu/querybuilder/) are no longer active.

**Comment by kpierceHST** [comment]
I've adjusted the text that's sent, replacing "https://querybuilder-lcp.mit.edu/" with the url that Tom suggested.  Below is the revised version.
Ken

-----
Thank you for your interest in the MIMIC Clinical Databases.
                                                                                                                                                                                   
Your request for access to the restricted-data files of the MIMIC-II and MIMIC-III Clinical Databases has been approved.  Your access should be activated shortly.
                                                                                                                                                                                   
For access, log in to PhysioNetWorks and click on the MIMIC-III (or MIMIC-II) Clinical Database link on your PhysioNetWorks home page. Please see http://mimic.physionet.org/gettingstarted/dbsetup/ for information about building the database from downloaded MIMIC data files.
                                                                                                                                                                                   
You may also log in to the MIMIC QueryBuilder (http://mimic.physionet.org/gettingstarted/querybuilder/) using your PhysioNetWorks username and password.

----

**Comment by tompollard** [comment]
Looks good, thanks Ken.
