### ISSUE TITLE
Questions: EEG Motor Movement/Imagery Dataset

### ISSUE THREAD

**Issue by azurexs** [MIT-LCP/physionet#26]
I am working on EEG Motor Movement/Imagery Dataset. I have a question of the experimental protocol. How much times have subjects repeated during visual stimulus(appearance of targets) for 4 tasks. According to task-description, subjects have repeated once in task 1. But why did it take 4.2 seconds finishing one grasp movement? If someone have answers, please help me to get rid of the questions.

**Comment by rgmark** [comment]
Hi,
I canot help  with this. I suggest you communicate with the contributor 
of the data if possible.
Best wishes!

R Mark

Roger G. Mark, M.D., Ph.D.
Professor of Health Sciences and Technology
   and of Electrical Engineering
Room E25-505
MIT
Cambridge, MA 02139
Tel 617-253-7818
Fax 617-258-7859

**Comment by JonathanZcl** [comment]
@azurexs 
Can you read the annotation file?

**Comment by azurexs** [comment]
hi, Jonathan,

i load the EDF+ files and open it with the function ReadEDF.m, I put it
hier, you can try with it.  The recordings, the  corresponding labels and
event-duration are inclusive in the output of this function.

Best regards
Sai

2017-05-02 15:46 GMT+02:00 JonathanZcl <notifications@github.com>:

**Comment by azurexs** [comment]
http://cn.mathworks.com/matlabcentral/fileexchange/38641-reading-and-saving-of-data-in-the-edf+?focused=3788255&tab=function.
Hier you can have this function.

2017-05-02 15:46 GMT+02:00 JonathanZcl <notifications@github.com>:

**Comment by Ri4el** [comment]
Does someone have any updates ?

**Comment by alistairewj** [comment]
As Roger said, we don't have this information. You'll have to contact the authors of the study.
