### ISSUE TITLE
PhysioBank ATM

### ISSUE THREAD

**Issue by benbastaki** [MIT-LCP/physionet#37]
Hi, why I can not load the ATM. now is for couple of days that I can not load the ATM to view the datasets.
Can anyone kindly tel me if this is a genaral issue or I only have it. I get Time out response.
I use the following link to log into ATM: https://physionet.org/physiotools/getting-started.shtml
Regards.

**Comment by tompollard** [comment]
@benbastaki thanks for reporting this issue, which has been fixed by Benjamin: https://www.physionet.org/cgi-bin/atm/ATM

**Comment by benbastaki** [comment]
@tompollard Thanks!
