### ISSUE TITLE
Trouble creating account

### ISSUE THREAD

**Issue by jefftienchow** [MIT-LCP/physionet#44]
When I give my email to create a physionetworks account, I don't get a confirmation email or anything to create my account. I have checked all of my folders, including junk e-mail, and the confirmation isn't in any of them. Could I get some help creating an account? Thanks.

**Comment by bemoody** [comment]
Sorry about that, our mail server was not working.  You should receive
the confirmation message shortly if you haven't already.

**Comment by atulkakrana** [comment]
Same here. I am trying to setup an account but not receiving confirmation email. Here is link that I am using to create account: https://physionet.org/pnw/login

**Comment by elfeto** [comment]
@atulkakrana I see that an account was created for you. If you cannot log in yet, please click on reset the password.
