### ISSUE TITLE
Unable to rsync mimic3wdb

### ISSUE THREAD

**Issue by ZhangAngus** [MIT-LCP/physionet#45]
Hello guys, in mimic2 waveform database, we can use command following to localize the database
`rsync -CaLvz physionet.org::mimic2wdb-matched /usr/database/mimic2wdb/matched`

but according to the mimic 3 waveform database instrution, we fail to download, it show below
`rsync -CaLvz physionet.org::mimic3wdb-matched /usr/database/mimic3wdb/matched`
`@ERROR: Unknown module 'mimic3wdb'
rsync error: error starting client-server protocol (code 5) at main.c(1648) [Receiver=3.1.2]`

Is there any solution? 
Thank you for your help

**Comment by alistairewj** [comment]
The `mimic3wdb` is not fully released yet, just a preliminary version. When it is fully released we will add in the rsync functionality. I'll close the issue here when that happens.

**Comment by alistairewj** [comment]
The database has been published. Please see https://physionet.org/physiobank/database/mimic3wdb/ for details.

You should be able to rsync the data. Please note that the `mimic3wdb` is just an alias for the `mimic2wdb` - which was also updated - these datasets are identical. `mimic3wdb-matched` is different from `mimic2wdb-matched` as the matched header files have changed but both can symlink to the same underlying data. Please download responsibly :)
