### ISSUE TITLE
Baseline Wander and Power Line Interference filtering of ECG data

### ISSUE THREAD

**Issue by Sophzr** [MIT-LCP/physionet#48]
Hello everyone,
I have a question regarding ECG pre-processing:
I am working with MIT-BIH Arrhythmia Database and want to extract RR interval. I am quite new to ECG analysis and feature extraction. So, based on literature, I used band-pass FIR filter (1-50Hz) to remove baseline wander and power line interference. However, when I use gqrs() function after filtering, it extracts about 6500 qrs signals which is not correct. I also tried gqrs() on data without filtering and it detected about 2270 qrs signals which is about right. Now, my question is that do I need to filter data before using gqrs()? 
Thanks

**Comment by alistairewj** [comment]
You can learn a bit more about gqrs by reading the [source code](http://www.physionet.org/physiotools/wfdb/app/gqrs.c), or by looking at the [configuration file](https://www.physionet.org/physiotools/wfdb/app/gqrs.conf). In particular this comment in the source code may shed some light:

```
/* sm() implements a trapezoidal low pass (smoothing) filter (with a gain of
   4*smdt) applied to input signal sig before the QRS matched filter qf().
   Before attempting to 'rewind' by more than BUFLN-smdt samples, reset smt
   and smt0.
 */
```
