### ISSUE TITLE
What does "lower noisy“ mean?

### ISSUE THREAD

**Issue by yuhang-lin** [MIT-LCP/physionet#52]
I am sorry that it's a silly question. But from [https://www.physionet.org/physiobank/database/html/mitdbdir/records.htm#106] it says "lower noisy". Which lead does it mean?

**Comment by alistairewj** [comment]
The annotation interface plotted leads from top to bottom, so I presume "lower noisy" means the second signal was noisy but the first one was clean. Maybe @rgmark can confirm!

**Comment by yuhang-lin** [comment]
Thank you @alistairewj
