### ISSUE TITLE
Question abt PTB Diagnostic ECG Database

### ISSUE THREAD

**Issue by asturia716** [MIT-LCP/physionet#53]
This is a question on a specific ECG Database on PTB

Based on the specifications stated on the [PTB Diagnostic ECG Database](https://www.physionet.org/physiobank/database/ptbdb/) webpage about the Bandwidth and Sampling rate of the digitized signals.

The bandwidth and sampling rate of the DAQ used during the trial are as followed: 
**Bandwidth:** 0 - 1 kHz (synchronous sampling of all channels)
**Sampling rate:** Signal is digitized at 1000 samples per second
 
According to Nyquist Sampling Theorem it states that the max bandwidth of any device should be no more than HALF of its sampling rate. Therefore for a DAQ with a 1000 sps sampling rate, the BEST bandwidth it can possibly get is only up to 500Hz.

According to this theorem, it would not be possible for any DAQ with the sampling rate of 1000 samples per second to achieve a bandwidth of 0-1 kHz. 

Could there be a possible mistype on the specs displayed on the webpage for the bandwidth or DAQ sampling rate? 

Or if the specifications are accurate, I am seeking an explanation for how it is possible for the DAQ to have the sampling rate of 1000 samples per second with the bandwidth of 0-1 kHz?

Anyone able to help resolve this question I have?

**Comment by alistairewj** [comment]
This is just semantics. You are correct that the sampling rate is 1 kHz, and that there is no usable frequency content above 500 Hz.
