### ISSUE TITLE
Lead Information Absent

### ISSUE THREAD

**Issue by manish-cere** [MIT-LCP/physionet#55]
Which leads are present in : 
1. MIT-BIH Atrial Fibrillation Database
2. The Long-Term AF Database
3. The MIT-BIH Normal Sinus Rhythm Database

Unlike in the  MIT-BIH Arrhythmia Database,  lead information is not specified explicitly in any of the data or header files

**Comment by alistairewj** [comment]
@rgmark gave some input:

> These waveforms are from Holter recordings. Standard ECG leads are not used, of course. The precordial electrodes are generally positioned to give one lead similar to V1 or V2 and the other lead is similar to V5 or V6 or lead II. Most commonly "ECG1" is V1 and "ECG2" is more like V5.
The leads are not important in the arrhythmia analysis.
