### ISSUE TITLE
How to get more information about a dataset?

### ISSUE THREAD

**Issue by pegah1362** [MIT-LCP/physionet#58]
Hi,

I have accessed the Physionet Data for CinC Challenge 2013, set A (https://physionet.org/challenge/2013/#ref-ann).
I understand that  different files are coming from different devices but there is not any other information about this dataset. I was wondering if there is a way to know what devices the data are recorded with.
I am specifically interested in one file “a03” since it shows a specific feature in the signal that our team is very interested in. We have seen this feature before and are trying to figure out if it is a hardware issue or a physiological issue, thus the importance of the device in question.
I would really appreciate it if you would please pass my question to the relevant team or guide me how to find the people who have provided this specific file to Physionet.

Thanks,

**Comment by alistairewj** [comment]
It's difficult to answer this question as part of the challenge is having a working model regardless of the underlying data collection. I would recommend contacting the authors of the special issue article here: http://iopscience.iop.org/article/10.1088/0967-3334/35/8/1521/meta ... and perhaps they can help.
