### ISSUE TITLE
Licenses are not clear

### ISSUE THREAD

**Issue by kwinkunks** [MIT-LCP/physionet#64]
I'm not a member of this community, so it's quite possible I'm missing something obvious, but may I suggest putting clear and unambiguous license statements on your datasets? 

Things like this > https://physionet.org/physiobank/database/ecgiddb/ < look really useful and interesting, but without a license I have to assume it's unlicensed and therefore off-limits for re-use. Is that the case?

Again, apologies if I'm missing something.

**Comment by tompollard** [comment]
@kwinkunks thanks for the feedback, and we agree that this is something that could be improved. We are in the process of rebuilding the platform and will be taking a number of steps to improve reusability of datasets, including clarifying usage rights.

**Comment by kwinkunks** [comment]
Thanks for the response Tom... Sounds great. I appreciate your work!

Please close the issue, as you wish.

**Comment by cx1111** [comment]
This will need to be updated. Anyway for now:
https://physionet.org/copying.shtml
