### ISSUE TITLE
Questions about the Arrhythmia database

### ISSUE THREAD

**Issue by VSuterio** [MIT-LCP/physionet#76]
I'm working with the physiobank database and i've some doubts that i'd like them to be esplanades.

Now, i'm using the 'rdann' function whos return: ann,anntype,subtype,chan,num,comments.

First I'd like to know what is: subtype, chan, and num?

Secondly, I suppose that the ann is the occurrence variable  of the others variables. This is, where it is the occurence of anntype. For example: ann = [5 8 11] and anntype = [A N V]. In ann=5 occured event A, in ann=8, the event N.

Thirdly, In some electrocardiograms, there is a sequence of N in ann, for example indicating the part of ECG that refers to normal beat. 
However, in the comments variable, there are some positions of the vector that is empty ([ ]). For example, comments = [(P [ ] [ ] [ ] (N [ ] [ ] [ ] (P]. I'd like to know if these empty spaces are also (P until (N and if the empty spaces between (N and (P are (N? What these empty spaces mean?

I hope I have been clear enough.

Thank you so much.

**Comment by cx1111** [comment]
This should answer the questions: https://physionet.org/physiobank/database/html/mitdbdir/intro.htm#symbols

**Comment by VSuterio** [comment]
I've saw this symbols list before, but I didn't find the information that I've been looking for. By these reason, I decided asked you. So, could you give me these informations?

Thank you.

Sincerely
