### ISSUE TITLE
Can't Create new Account: Timeout

### ISSUE THREAD

**Issue by DeastinY** [MIT-LCP/physionet#79]
When I try to create an account through https://physionet.org/pnw/ or reset a password I get a timeout.
Any ideas?
```

Gateway Timeout

The gateway did not receive a timely response from the upstream server or application.
Apache/2.4.25 (Debian) mod_auth_pgsql/2.0.3 mod_auth_tkt/2.1.0 OpenSSL/1.0.2l Server at physionet.org Port 443
```

**Comment by DeastinY** [comment]
It worked. After two days worth of trying.  
Maybe it was a temporary peek in server load, but imho it is worth investigating :wink:

**Comment by tompollard** [comment]
Thanks @DeastinY, and sorry for the clunkiness. We are in the process of completely rebuilding PhysioNet, which I hope will improve things in the longer run. We're aiming to release the new site for testing within the year.
