### ISSUE TITLE
header in slpdb not conform to physionet header specifications 

### ISSUE THREAD

**Issue by hojo0590** [MIT-LCP/physionet#83]
One of the header files contained in the MIT-BH Polysomnographic Database is not conform to PhyioNet header specifications. Its year in the base date string is given with two digits only - instead of the specified four (e.g. 89 instead of 1989).
The file of concern is https://physionet.org/physiobank/database/slpdb/slp32.hea

**Comment by cx1111** [comment]
Fixed, thanks.
