### ISSUE TITLE
How to obtain test set score of Apnea-ECG database?

### ISSUE THREAD

**Issue by zzklove3344** [MIT-LCP/physionet#85]
Hello, 

I want to get my score of test set of Apnea-ECG database, x01-x35. I followed the link about how to obtain my score, [link](https://physionet.org/physiobank/database/apnea-ecg/challenge/). However, no web page can be upload my entry. So, can you gived me a link to upload my entry or another way to obtain test set score?

Thank you in advance.

**Comment by MADSOLSEN** [comment]
https://www.physionet.org/challenge/2000/event-2-answers

**Comment by zzklove3344** [comment]
> https://www.physionet.org/challenge/2000/event-2-answers

Thank you very much!
