### ISSUE TITLE
Glasgow Coma Score for Intubated or sedated patients

### ISSUE THREAD

**Issue by gilmervaldes** [MIT-LCP/physionet#88]
Hi All

In the article: "The MIMIC Code Repository: enabling reproducibility in
critical care research "

https://academic.oup.com/jamia/advance-article-pdf/doi/10.1093/jamia/ocx084/20306688/ocx084.pdf

it says "... In contrast, the documentation of GCS
for these patients  (sedated or intubated, patients whose GCS can not be extracted) in the MIMIC-III database is usually a value of 3, the minimum value, with a note that they are unable to assess the
patients...." 

Is this also true for MIMIC II? Is there a link that confirms this?

Thanks for your help!

**Comment by alistairewj** [comment]
The raw data for MIMIC-II and MIMIC-III is largely the same (MIMIC-III has an improved structure and more data), so this will be the same in MIMIC-II. However MIMIC-III has been public for almost 3 years now so you should probably upgrade!
