### ISSUE TITLE
how we can download a full databse??

### ISSUE THREAD

**Issue by shefs0709** [MIT-LCP/physionet#90]
Sir
how to download full database??
As my project is based on SCD detection ( ECG signals) so we want to download the entire file in a record till SCD occurs.
we need large samples size for SDDB database, we try download it from physionetATM but we fail as the downloaded data is only 3MB and does not contain all samples.
please help regarding the issue..
thank you in Advance....

**Comment by alistairewj** [comment]
See the tutorial here for some guidance: https://physionet.org/physiobank/about.shtml#downloading

Feel free to reopen if that doesn't work for you.

**Comment by shefs0709** [comment]
sir
I downloaded the zip file of respective record but it does not contain any mat-file.

**Comment by alistairewj** [comment]
It is likely not stored in a MATLAB format but rather a format readable by WFDB. 

https://physionet.org/tutorials/physiobank-text.shtml

**Comment by shefs0709** [comment]
sir
I am still unable to do it..
as I want 13,993,632 bytes or more byte of data..
