### ISSUE TITLE
Duplicate sleep-edf database

### ISSUE THREAD

**Issue by massich** [MIT-LCP/physionet#97]
Recently in mne-python we added a data fetcher for the sleep-edf database along with [an example](https://mne-tools.github.io/dev/auto_tutorials/plot_sleep.html) (in the following PR https://github.com/mne-tools/mne-python/pull/5718)

Initially we included the `The Sleep-EDF Database [Expanded]` from https://physionet.org/pn4/sleep-edfx/ We just realized that there's a more complete version of the same dataset also called `The Sleep-EDF Database [Expanded]` here  https://physionet.org/physiobank/database/sleep-edfx/ At this point we are migrating our fetcher from the former to the latter.

We understand that the former might remain online for historical reasons, but it would be good to clearly state (red banner or something) that the complete version is also available.

Apart from that, we also realized that the complete version of the dataset does not include the `{MD5, SHA1, SHA256}SUMS` of the `.edf` files. We have computed them, but it would be great if they were available from your side. 

cc: @hubertjb

**Comment by tompollard** [comment]
Thanks for the note @massich. We're in the process of rebuilding the PhysioNet platform, and will be developing functionality for clearer labelling of versions. The new system will also ensure that all databases include a standard set of files, including the list of hashes. For the meantime, we'll look into updating the project as suggested.

**Comment by cx1111** [comment]
Thank you for pointing this out. I was supposed to remove the smaller one. Sorry for the inconvenience.

I've also generated the checksums.

**Comment by massich** [comment]
@cx1111 removed the `index.html` and the rest of the data.

maybe you should consider to let the data still there for a while without the entry point.
