### ISSUE TITLE
MIMIC-CXR data access 

### ISSUE THREAD

**Issue by andinet** [MIT-LCP/physionet#98]
Hi,

I have a data use agreement (DUA) that was approved and I have access the PhysioNet restricted databases. I was able to access the eICU database with no problems. But, I am trying to get access to MIMIC-CXR but I am running into an issue

https://physionet.org/works/MIMICCXR/

1) When I try the "Authorized users" option,  I get the error. "The PhysioNet server could not verify that you are authorized to access this workspace". I confirmed my username and password and it works.

2) When I try "Apply for access" option, I am informed I have a data use agreement in place and I don't need a new one.

Do I need a new data use agreement for the MIMIC-CXR database? 

Thanks for your help!
Andinet

**Comment by alistairewj** [comment]
Hi Andinet - at the moment the answer is yes, you do need to sign a new data use agreement. This data use agreement is identical to the one you signed for eICU.

> 2\. When I try "Apply for access" option, I am informed I have a data use agreement in place and I don't need a new one.

When you see this screen, click "Yes", and confirm that you would like to submit another DUA, even though you already have one in the system.
Apologies as this is a bit redundant and the message is vague. We are in the middle of updating our process so in the future this will be clearer!

**Comment by andinet** [comment]
Thanks Alistair. I just submitted a new DUA.

Best,
Andinet
